modLoader="javafml"
loaderVersion="[46,)"
license="MIT"
issueTrackerURL="https://github.com/PandaDap2006/Pandas-Extra-Details/issues"
displayURL="https://modrinth.com/mod/pandas-extra-details"
showAsResourcePack=false

[[mods]]
modId="extra_details"
version="${version}"
displayName="Panda's Extra Details"
logoFile="icon.png"
authors="PandaMods/The Panda Oliver"
description="A mod that adds extra Details to Minecraft for both Forge and Fabric"

[[dependencies.extra_details]]
   modId="forge"
   mandatory=true
   versionRange="[46,)"
   ordering="NONE"
   side="CLIENT"
[[dependencies.extra_details]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.20,1.21)"
   ordering="NONE"
   side="CLIENT"
[[dependencies.fallingtrees]]
   modId="cloth_config"
   mandatory=true
   versionRange="[11.0.99,)"
   ordering="NONE"
   side="CLIENT"
[[dependencies.fallingtrees]]
   modId="architectury"
   mandatory=true
   versionRange="[9.0.8,)"
   ordering="NONE"
   side="CLIENT"